- ignore: {name: Eta reduce}
- ignore: {name: Redundant do}
- ignore: {name: Use let}
- ignore: {name: Use newtype instead of data}
- ignore: {name: Redundant return}
- functions:
  - {name: undefined, within: []}
