- ignore: {name: Eta reduce}
- ignore: {name: Redundant do}
- ignore: {name: Use let}
- ignore: {name: Use newtype instead of data}
- ignore: {name: Redundant return}
- ignore: {name: Parse error}
- ignore: {name: Use ||}
- functions:
  - {name: undefined}

- arguments:
  - -XAutoDeriveTypeable
  - -XBangPatterns
  - -XConstraintKinds
  - -XDefaultSignatures
  - -XDataKinds
  - -XFlexibleContexts
  - -XFlexibleInstances
  - -XFunctionalDependencies
  - -XGADTs
  - -XInstanceSigs
  - -XKindSignatures
  - -XLambdaCase
  - -XMultiParamTypeClasses
  - -XMultiWayIf
  - -XNamedFieldPuns
  - -XNoImplicitPrelude
  - -XOverloadedLabels
  - -XOverloadedStrings
  - -XPatternSynonyms
  - -XPolyKinds
  - -XRankNTypes
  - -XRecordWildCards
  - -XScopedTypeVariables
  - -XStandaloneDeriving
  - -XStrictData
  - -XTupleSections
  - -XTypeApplications
  - -XTypeFamilies
  - -XTypeFamilyDependencies
  - -XTypeOperators
  - -XViewPatterns
