dist: xenial

language: generic

cache:
  directories:
  - $HOME/.stack

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack --no-terminal --install-ghc test --only-dependencies
- git clone https://github.com/haskell/haskell-ide-engine
- (cd haskell-ide-engine; make install hie-8.4.4)


script:
- stack --no-terminal test
