name:                nvim-hs-lsp
version:             0.1.0.0

default-extensions:
- AutoDeriveTypeable
- BangPatterns
- ConstraintKinds
- DefaultSignatures
- DataKinds
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NoImplicitPrelude
- OverloadedLabels
- OverloadedStrings
- PatternSynonyms
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- StrictData
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators
- ViewPatterns

custom-setup:
  dependencies:
    - base >= 4.7 && < 5
    - Cabal
    - cabal-doctest >= 1 && < 1.1
    - hspec

dependencies:
- base >= 4.7 && < 5
- rio >= 0.1.3.0

library:
  source-dirs: src
  ghc-options:
  - -Wall
    #- -fprint-explicit-kinds
  dependencies:
  - nvim-hs >= 1.0.0.0
    # 0.2.4の testWithEmbeddedNeovim は壊れている模様
  - nvim-hs-contrib
  - aeson
  - constraints
  - containers
  - unordered-containers
  - extensible
  - hashable
  - lens
  - process
  - safe
  - singletons
  - text
  - stm
  - bytestring
  - mtl
  - async
  - extra
  - deepseq
  - unliftio
  - either

tests:
  doctests:
    source-dirs:   test
    main:          doctests.hs
    other-modules:
    - Build_doctests
    dependencies:
    - doctest
  tmp:
    source-dirs: test
    main:        tmp.hs
    other-modules: []
    dependencies:
    - nvim-hs
    - nvim-hs-lsp
    - stm
    - lens
    - process
    - unliftio
  spec:
    source-dirs:   test
    main:          Spec.hs
    dependencies:
    - nvim-hs
    - nvim-hs-lsp
    - hspec
    - unliftio
    - process
    - directory
    - resourcet
    - extensible
    - transformers
    - mtl

