name:                nvim-hs-lsp
version:             0.1.0.0

custom-setup:
  dependencies:
    - base >= 4.7 && < 5
    - Cabal
    - cabal-doctest >= 1 && < 1.1

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -Wall
  dependencies:
  - nvim-hs >= 0.2.2
  - lifted-base
  - resourcet
  - ansi-wl-pprint
  - aeson
  - constraints
  - containers
  - unordered-containers
  - deepseq
  - directory
  - extensible
  - hashable
  - hslogger
  - lens
  - process
  - safe
  - singletons
  - text
  - stm
  - bytestring
  - mtl

executables:
  tmp:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - nvim-hs >= 0.2.2
    - nvim-hs-lsp
    - stm
    - bytestring
    - mtl

tests:
  doctests:
    source-dirs:   test
    main:          doctests.hs
    other-modules:
      - Build_doctests
    dependencies:
      - doctest

