name:                nvim-hs-lsp
version:             0.2.0.0

default-extensions:
- DeriveDataTypeable
- BangPatterns
- ConstraintKinds
- DefaultSignatures
- DataKinds
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedLabels
- OverloadedStrings
- PatternSynonyms
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- StrictData
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators
- ViewPatterns

custom-setup:
  dependencies:
    - base >= 4.7 && < 5
    - Cabal
    - cabal-doctest >= 1 && < 1.1
    - hspec

dependencies:
- base >= 4.7 && < 5
- rio >= 0.1.5.0
- nvim-hs >= 2.0.0.0
- generic-lens >= 1.1.0.0
- lens

executables:
  nvim-hs-lsp:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - nvim-hs-lsp

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fobject-code
    #- -fprint-explicit-kinds
  dependencies:
  - nvim-hs-contrib >= 2.0.0.0
  - aeson
  - constraints
  - extensible >= 0.5
  - lens
  - path
  - text
  - process
  - singletons
  - stm
  - bytestring
  - mtl
  - async
  - extra
  - deepseq
  - unliftio
  - either
  - resourcet
  - typenums

tests:
  doctests:
    source-dirs:   test
    main:          doctests.hs
    generated-other-modules:
    - Build_doctests
    other-modules:
    - Build_doctests
    dependencies:
    - doctest
  tmp:
    source-dirs: test
    main:        tmp.hs
    other-modules: []
    dependencies:
    - nvim-hs-lsp
    - stm
    - lens
    - process
    - unliftio
  spec:
    source-dirs:   test
    main:          Spec.hs
    dependencies:
    - nvim-hs-lsp
    - aeson
    - hspec
    - path
    - directory
    - extensible

