name:                nvim-hs-lsp
version:             0.1.0.0


custom-setup:
  dependencies:
    - base >= 4.7 && < 5
    - Cabal
    - cabal-doctest >= 1 && < 1.1
    - hspec

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -Wall
    #- -fprint-explicit-kinds
  dependencies:
  - nvim-hs >= 1.0.0.0
    # 0.2.4の testWithEmbeddedNeovim は壊れている模様
  - aeson
  - constraints
  - containers
  - unordered-containers
  - extensible
  - hashable
  - hslogger
  - lens
  - process
  - safe
  - singletons
  - text
  - stm
  - bytestring
  - mtl
  - async
  - extra
  - deepseq
  - unliftio

tests:
  doctests:
    source-dirs:   test
    main:          doctests.hs
    other-modules:
    - Build_doctests
    dependencies:
    - doctest
  tmp:
    source-dirs: test
    main:        tmp.hs
    other-modules: []
    dependencies:
    - nvim-hs
    - nvim-hs-lsp
    - stm
    - lens
    - process
    - unliftio
  quick:
    source-dirs:   test
    main:          Spec.hs
    dependencies:
    - nvim-hs
    - nvim-hs-lsp
    - hspec
    - QuickCheck
    - unliftio
    - prettyprinter
    - process
    - directory
    - resourcet
    - extensible
    - prettyprinter-ansi-terminal
    - transformers
    - mtl

