
#resolver: lts-11.17
#
#extra-deps:
#- nvim-hs-1.0.0.2
#- nvim-hs-contrib-1.0.0.0
#- xformat-0.1.2.1
#- extensible-0.4.7
#- rio-0.1.5.0
#- typed-process-0.2.2.0
#- unliftio-0.2.7.0

resolver: lts-12.12

extra-deps:
- nvim-hs-1.0.0.2
#- nvim-hs-contrib-1.0.0.0
#- extensible-0.4.8
#- rio-0.1.5.0
#- typed-process-0.2.2.0
#- unliftio-0.2.7.0
