name:                test-example
version:             0.1.0.0
github:              "Hogeyama/test-example"
license:             BSD3

default-extensions:
- ExplicitForAll

dependencies:
- base >= 4.7 && < 5
- bytestring

library:
  source-dirs: .

