version: 2

aliases:
  - &default_env
    CACHE_KEY: TMP
    SUB_CACHE_KEY: 11
    STACK_VERSION: 1.9.1
    PRE_CACHE_KEY: TMP
  - &create_cache_key_file
    run:
      name: Create cache control key file
      command: |
        echo $CIRCLE_JOB
        echo $CACHE_KEY     > cache_key
        echo $SUB_CACHE_KEY > sub_cache_key
        cat  $STACK_YAML    > .stack.yaml || touch .stack.yaml
        echo $PRE_CACHE_KEY > pre_cache_key
  - &restore_build_results
    restore_cache:
      keys:
        - cache-{{ checksum "cache_key" }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum ".stack.yaml" }}-{{ checksum "package.yaml" }}-{{ checksum "sub_cache_key" }}
        - cache-{{ checksum "cache_key" }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum ".stack.yaml" }}-{{ checksum "package.yaml" }}
        - cache-{{ checksum "cache_key" }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum ".stack.yaml" }}
        - cache-{{ checksum "cache_key" }}-{{ .Environment.CIRCLE_JOB }}

        - cache-{{ checksum "cache_key" }}-{{ checksum ".stack.yaml" }}-{{ checksum "package.yaml" }}-{{ checksum "sub_cache_key" }}
        - cache-{{ checksum "cache_key" }}-{{ checksum ".stack.yaml" }}-{{ checksum "package.yaml" }}
        - cache-{{ checksum "cache_key" }}-{{ checksum ".stack.yaml" }}
        - cache-{{ checksum "cache_key" }}
        - cache-{{ checksum "cache_key" }}
  - &save_build_results
      save_cache:
        key:
        - cache-{{ checksum "cache_key" }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum ".stack.yaml" }}-{{ checksum "package.yaml" }}-{{ checksum "sub_cache_key" }}
        paths:
          - ~/haskell-ide-engine
          - ~/.local/bin
          - ~/.stack
          - ~/.cabal
          - ~/.hoogle
          - ~/.ghc
          - .stack-work
        when:
          always
  - &display_stack_version
    run:
      name: Display stack version
      command: |
        stack --no-terminal upgrade --binary-version=$STACK_VERSION
        stack --no-terminal --version
  - &set_path
      run:
        name: Set PATH
        command: |
          export PATH=~/.cabal/bin:~/.local/bin:$PATH
          mkdir -p ~/.local/bin
          echo $PATH
          export WORKING_DIRECTORY=`pwd` # 何故かworking_directoryが効かない
  - &install_nvim
      run:
        name: Install Neovim
        command: |
          curl https://github.com/neovim/neovim/releases/download/v0.3.4/nvim.appimage -L -o nvim
          chmod u+x nvim
          ./nvim --appimage-extract
          mv ./squashfs-root/usr/bin/nvim $HOME/.local/bin
          nvim --version
  - &build_hie_pre
      run:
        name: Prepare for building hie
        command: |
          if [ -d ~/haskell-ide-engine ]
          then
            echo "cached"
          else
            git clone https://github.com/haskell/haskell-ide-engine ~/haskell-ide-engine
          fi
          (cd ~/haskell-ide-engine; git checkout ec5e34c)
          (cd ~/haskell-ide-engine; ./install.hs submodules)
          (cd ~/haskell-ide-engine; ./install.hs cabal)
  - &build_hie_deps # 分けてbuildしないとメモリを使い果たして死ぬので悲しい気持ちになります
      run:
        name: Build hie dependencies
        command: |
          cd ~/haskell-ide-engine
          if [[ -z "$STACK_YAML" ]]
          then
            cabal new-build ghc-exactprint
            cabal new-build cabal-helper
            cabal new-build HaRe
            cabal new-build hie-plugin-api
            cabal new-build ghc-mod
            cabal new-build
          else
            # stack clean --no-terminal --stack-yaml=stack-"$GHC_VERSION".yaml
            stack build --no-terminal --stack-yaml=stack-"$GHC_VERSION".yaml ghc-exactprint
            stack build --no-terminal --stack-yaml=stack-"$GHC_VERSION".yaml cabal-helper
            stack build --no-terminal --stack-yaml=stack-"$GHC_VERSION".yaml HaRe
            stack build --no-terminal --stack-yaml=stack-"$GHC_VERSION".yaml hie-plugin-api
            stack build --no-terminal --stack-yaml=stack-"$GHC_VERSION".yaml ghc-mod
            stack build --no-terminal --stack-yaml=stack-"$GHC_VERSION".yaml
          fi
          cd $WORKING_DIRECTORY
  - &build_hie
      run:
        name: Build hie for test
        command: |
          cd ~/haskell-ide-engine
          if [[ -z "$STACK_YAML" ]]
          then
            which hie || ./install.hs cabal-hie-"$GHC_VERSION"
            ./install.hs cabal-build-doc-"$GHC_VERSION"
          else
            which hie || ./install.hs hie-"$GHC_VERSION"
            ./install.hs build-doc-"$GHC_VERSION"
          fi
          cd $WORKING_DIRECTORY
  - &default
      docker:
        - image: quay.io/haskell_works/stack-build-minimal
      steps:
        - checkout
        - *create_cache_key_file
        - *set_path
        - *install_nvim
        - *restore_build_results
        - *display_stack_version
        - *build_hie_pre
        - *build_hie_deps
        - *build_hie
        - run:
            name: Install dependencies
            command: |
              echo $STACK_YAML
              if [[ -z "$STACK_YAML" ]]
              then
                cabal new-install hpack
                hpack
                cabal new-build -j1 --dependencies-only
              else
                stack --stack-yaml=$STACK_YAML test -j 1 --only-dependencies --no-terminal --no-run-tests
              fi
            no_output_timeout: 120m
        - run:
            name: Run stack test
            command: |
              export NVIM_LISTEN_ADDRESS=~/nvim_listen_address
              export VIM=./squashfs-root/usr/share/nvim
              nvim --headless &
              if [[ -z "$STACK_YAML" ]]
              then
                cabal new-test || (cat /tmp/test-hie.log && exit 1)
              else
                stack --stack-yaml=$STACK_YAML test --fast --no-terminal || (cat /tmp/test-hie.log && exit 1)
              fi
              # kill `pgrep nvim`
        - run:
            name: Run stack test --pedantic --no-terminal
            command: |
              if [[ -z "$STACK_YAML" ]]
              then
                echo "skip"
              else
                stack --stack-yaml=$STACK_YAML clean
                stack --stack-yaml=$STACK_YAML test --pedantic --fast --no-run-tests --no-terminal
              fi
        - *save_build_results

jobs:
  stack-8.6.4:
    environment:
      - *default_env
      - GHC_VERSION: 8.6.4
      - STACK_YAML: stack-8.6.4.yaml
    docker:
      - image: quay.io/haskell_works/stack-build-minimal
    <<: *default
  stack-8.4.4:
    environment:
      - *default_env
      - GHC_VERSION: 8.4.4
      - STACK_YAML: stack-8.4.4.yaml
    docker:
      - image: quay.io/haskell_works/stack-build-minimal
    <<: *default
  cabal-8.4.4:
    environment:
      - *default_env
      - GHC_VERSION: 8.4.4
    docker:
      - image: quay.io/haskell_works/ghc-8.4.4
    <<: *default

workflows:
  version: 2
  all:
    jobs:
      - stack-8.6.4:
          filters:
            branches:
              only:
                - master
                - circleci-test
      - cabal-8.4.4:
          filters:
            branches:
              only:
                - master
                - circleci-test
      # - stack-8.4.4:
      #     filters:
      #       branches:
      #         only:
      #           - master
      #           - circleci-test

